<?php
// module/Album/view/album/album/index.phtml:

$title = 'Moji albumi';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('album', ['action' => 'add']) ?>">Dodaj novi</a>
</p>

<div class="row">
    <div class="col-md-8 md-offset-2">
        <table class="table">
        <tr>
            <th>Naslov</th>
            <th>Pevač</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($albums as $album) : ?>
            <tr>
                <td><?= $this->escapeHtml($album->title) ?></td>
                <td><?= $this->escapeHtml($album->artist) ?></td>
                <td>
                    <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>"><span class="label label-success">Izmeni</span></a>
                    <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>"><span class="label label-danger">Obriši</span></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>